version: 2
project_name: beacon

builds:
- skip: true

changelog:
  sort: asc
  use: git

release:
  github:
    owner: sverdejot
    name: beacon

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT"

